### ISSUE TITLE
discord server?

### ISSUE THREAD

**Issue by fawnchunk** [pickle69420/picklebox#13]
when are the plans for the server

**Comment by pickle69420** [comment]
none, there will soon be a chat feature (once i leave middle school because they treatened me)

**Comment by Weeblizer** [comment]
So we need to wait until next year for the release of pickle box? So sad. Waaa. Waaaaaaaaaaa. Wa. Good luck though.

**Comment by TheGlitchedPhoenix** [comment]
Sadge :(
Idk if rsd is gonna block my pr-xy next year so I'm always looking for an alt

oof

**Comment by TheGlitchedPhoenix** [comment]
> none, there will soon be a chat feature (once i leave middle school because they treatened me)

wait WHAT

**Comment by pickle69420** [comment]
I'm so sorry for now my principal is threatening me. I'm working on a new project.😭😭😭😭

**Comment by 8lat** [comment]
@pickle69420 if he threatens you threaten him by saying "I have over 100 unblocked links I will give to everyone" or som like that
