### ISSUE TITLE
Help with availability 

### ISSUE THREAD

**Issue by Fr00ger** [pickle69420/picklebox#14]
Is pickle box bookmarklet available yet?

**Comment by vidio-boy** [comment]
No, pickle is still working on it. His principle threatened him and the project is currently at a standstill. It should be finished sometime next school year, so watch the project or follow pickle to get updates.

**Comment by vidio-boy** [comment]
> Is pickle box bookmarklet available yet?
No, pickle is still working on it. His principle threatened him and the project is currently at a standstill. It should be finished sometime next school year, so watch the project or follow pickle to get updates.

**Comment by SnesLover22** [comment]
no other project? pickle is being watched rn

**Comment by pickle69420** [comment]
No, it's not a proxy, it's a personal thing of mine. It's called evol-tech and I haven't made it public yet. I'll tell you when.

**Comment by KomodoYT** [comment]
I am very exited for it to be ready

**Comment by KomodoYT** [comment]
Will it work on school chromebook?

**Comment by pickle69420** [comment]
I don't know, but it should work if bookmarklets are available

**Comment by pickle69420** [comment]
> ftr you could use codesandbox for the dev

I'm so sad but it's blocked for me

**Comment by KomodoYT** [comment]
> I don't know, but it should work if bookmarklets are available

do you mean it works now?

**Comment by pickle69420** [comment]
No as i said my princibal threatened me

**Comment by KomodoYT** [comment]
Oh okay.

**Comment by TheGlitchedPhoenix** [comment]
WE NEED MORE PROXXIIIIIESSSSSSSSSSSSSSSSSSS
(ahhh my eyes-)

**Comment by TheGlitchedPhoenix** [comment]
please send me some uv prrxies with cyclic render or csb
