### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by SnesLover22** [pickle69420/picklebox#2]
yo if you need games, contact me, I got TONS of games you can use, lots of HTML files. I got u, bro

**Comment by pickle69420** [comment]
Thanks a lot man, I'll remember to!

**Comment by SnesLover22** [comment]
lol sorry I didn't see this comment earlier! hey, just email me and alls good! its md27396@owassops.org. if it doesn't work, use sneslover23@gmail.com. anyway good luck on the project!

**Comment by pickle69420** [comment]
Thanks for the support.

**Comment by SnesLover22** [comment]
no problem, man! (The more projects like these I find, the more I can add to my site, and to more those small creators get downloads/uses of their repos! Its a circle, ya know? lol)

**Comment by maxkaos8** [comment]
> yo if you need games, contact me, I got TONS of games you can use, lots of HTML files. I got u, bro

Is there any chance you could shoot me some of those games? Email's maxkaos3@gmail.com

**Comment by SnesLover22** [comment]
sure dude
