### ISSUE TITLE
where is da pickle??

### ISSUE THREAD

**Issue by Binary0universe** [pickle69420/picklebox#20]
i have not seen picklebox get any commits (other then the dev branch- and there were only 5 commits ahead) scince the last month of school so what happened?? can the dev tell me??

**Comment by Binary0universe** [comment]
if there is no responce, i might fork this and """""finish it"""""

**Comment by TheGlitchedPhoenix** [comment]
Hey ben, Pickle69420 was threatened by his authorities with expulsion. He's
at a standstill right now until he gets outta the school district.
