### ISSUE TITLE
how do i use as bookmarklet

### ISSUE THREAD

**Issue by narmadikmanokat** [pickle69420/picklebox#21]
how do i copy the bookmarklet

**Comment by kerbalis** [comment]
i dont think its finished yet but i  culd b wrong

**Comment by ghost** [comment]
@valium

Open the .js file in your browser or in github and tripleclick the long
line of text
then copy the text and right-click your bookmarks bar and click paste

**Comment by kerbalis** [comment]
which one theres like 7

**Comment by pickle69420** [comment]
you cant bruh
