### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ghost** [pickle69420/picklebox#29]
Where can I find the code for the bookmarklet?
I cant seem to find it.

**Comment by Bluubr** [comment]
how do you use

**Comment by Iamhungryrightnow** [comment]
Where do you find it?

**Comment by om3ga6400** [comment]
@IceyMisfitZ @Iamhungryrightnow @Bluubr read the readme before opening an issue

**Comment by om3ga6400** [comment]
@pickle69420 close this if you can
