### ISSUE TITLE
⚠ANNOUNCEMENT⚠

### ISSUE THREAD

**Issue by pickle69420** [pickle69420/picklebox#8]
Recently, I was in the middle of developing the proxy browser, when suddenly my testing link got blocked 😥.

If anyone can help me by hosting a new website, please comment down below.

Please help if you support this project...

**Comment by SnesLover22** [comment]
use github pages if applicable, OR use heroku, vercel, netlify... Oh wait no use glitch.me it has a console and everything

**Comment by pickle69420** [comment]
@SnesLover22 these are all blocked and most of them are static sites. I need a custom domain.

**Comment by SnesLover22** [comment]
even glitch!? wow I use glitch for my ultraviolet proxy it should work unless its blocked for you...

**Comment by KUKHUA** [comment]
I heard https://deta.space/ may be good, It has 10GB for storage and unlimited bandwidth, I've been told.

**Comment by pickle69420** [comment]
Wow thanks I'll check it out

**Comment by pickle69420** [comment]
Update: I don't think this is hosting. Im not quite sure. It must be one of those 'Web6' type projects.

**Comment by SnesLover22** [comment]
is cyclic blocked for you?

**Comment by KUKHUA** [comment]
> Update: I don't think this is hosting. Im not quite sure. It must be one of those 'Web6' type projects.

Oh.. I preety sure you can create your own "apps" on there.

**Comment by MicroChipKali** [comment]
You should try to use cyclic which is a very good hosting provider

**Comment by TheGlitchedPhoenix** [comment]
Try google sites and use a full HTML embed
it works sometimes but if it's rockwood you're dealing with then you don't have many options

**Comment by TheGlitchedPhoenix** [comment]
sadge.

**Comment by TheGlitchedPhoenix** [comment]
I use Cyclic (GoGuardian doesn't block subdomains usually) and Netlify. However, GG blocks these sites on the default (not app.netlify.app, but netlify.app)

**Comment by Username93939** [comment]
> use github pages if applicable, OR use heroku, vercel, netlify... Oh wait no use glitch.me it has a console and everything

I personally prefer cyclic, it has a console, free authentication, free custom .cyclic.app domains, etc.
